### ISSUE TITLE
- The printer or class does not exist - when specifying a valid destination option.

### ISSUE THREAD

**Issue by ghost** [armetiz/node-printer-lp#2]
I can run the following command without problem:

lp -d SAMSUNG2240 -o media=letter /home/diegoalberto/Current/wolf-dev/.php/exports/sku72603_20150415111701.pdf

But when I try to do in my script:

var jobFile = printer.printFile("/home/diegoalberto/Current/wolf-dev/.php/exports/sku72603_20150415111701.pdf", {
                                            destination: "SAMSUNG2240"
                                        }, "jobFile");

It always returns - info: error jobFile, error: lp: The printer or class does not exist. -

How can specify the printer name dynamically?

Thanks in advance.

**Comment by armetiz** [comment]
Hi @diegoalberto ,

Sorry, but this repository is not maintained any more.

Regards.

**Comment by ghost** [comment]
Hi @armetiz, is there any other repository that you would recommend? I liked your approach.

**Comment by armetiz** [comment]
No sorry..

**Comment by armetiz** [comment]
If you want, you can fork it and solve the problem by yourself; there is no problem about it.

**Comment by ghost** [comment]
You're right:

https://www.npmjs.com/package/node-printer-lp-complete
https://github.com/diegoalberto/node-printer-lp-complete

Thanks!
